name: scratchapi
projectname: test

database:
  containerPort: "5432"
  image:
    repository: seyio91.azurecr.io/postgres
    tag: latest
    pullPolicy: IfNotPresent
  tier: database
  servicePort: "5432"
  serviceType: ClusterIP
  replicaCount: 1
  dbName: scratchdb

backend:
  containerPort: 3000
  image: 
    repository: seyio91.azurecr.io/scratchapi
    tag: v1
    pullPolicy: IfNotPresent
  tier: backend
  servicePort: 80
  serviceType: ClusterIP
  replicaCount: 1
  # serviceType: NodePort
  # nodePort: 30007

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

secretsMap:
  db_username: mydbuser
  db_password: somerandompassword

imagePullSecrets:
  - name: regcred