apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "scratchapi.databasename" . }}"
  labels:
    {{- include "scratchapi.dbLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  selector:
    matchLabels:
      {{- include "scratchapi.dbSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scratchapi.dbSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.dbName }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: db_password
          ports:
            - name: http
              containerPort: {{ .Values.database.containerPort }}
              protocol: TCP
