apiVersion: v1
kind: Service
metadata:
  name: {{ include "scratchapi.servicename" . }}
  labels:
    {{- include "scratchapi.appLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.serviceType }}
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    {{- include "scratchapi.appSelectorLabels" . | nindent 4 }}
