name: Main Branch Build

on:
  push:
    branches: [ main ]
    paths:
      - api/**
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          push: true
          tags: |
            seyio/scratchapi:latest
            seyio/scratchapi:${{ steps.slug.outputs.sha8 }}